<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\RehoukrelTemplate.Core.Infra\RehoukrelTemplate.Core.Infra.csproj" />
      <ProjectReference Include="..\RehoukrelTemplate.Hello.Application\RehoukrelTemplate.Hello.Application.csproj" />
    </ItemGroup>

</Project>
